get:
  operationId: getFailedDeployments
  summary: List of failed deployments
  description: Retrieves a list of the failed deployments
  tags:
    - Content Server
  responses:
    '200':
      description: Failed deployments list
      content:
        application/json; charset=utf-8:
          schema:
            $ref: ../../components/schemas/content/200-failed-deployments.yaml
          examples:
            default:
              $ref: ../../components/examples/content/200-failed-deployments.json
